In [1]:
import numpy as np 

In [5]:
#Creating a scalar array in numpy
s = np.array(5)
#Shape of our scala array (it is 0 dimensional data)
print(s.shape)

#Checking the type of our array
print(type(s))

()
<class 'numpy.ndarray'>


In [8]:
#Creating a vector
v = np.array([1,2,3])

#Accessing a element
print(v[2])

#Printing elements from position 2

print(v[1:])

3
[2 3]


In [9]:
#You can even make matrices
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Random multi-dim tensor

t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

print(t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


In [13]:
#changing shape of array

v = np.array([1,2,3,4])

print(np.shape(v))
print(v)
print("")

v = v.reshape(1,4)
print(np.shape(v))
print(v)
print("")

v = v.reshape(4,1)
print(np.shape(v))
print(v)
print("")

(4,)
[1 2 3 4]

(1, 4)
[[1 2 3 4]]

(4, 1)
[[1]
 [2]
 [3]
 [4]]

